name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Describe your issue and any ideas on how to solve it'
        pr-message: 'Mark your header with FEAT/CHANGE etc and a short title on what the PR is about'
